import '../../app/domain/models/discoteca_model.dart';



final List<Discoteca> discotecasList = [
  const Discoteca(
    id:'1',
    name: 'Opium Barcelona',
    address: 'Passeig Marítim de la Barceloneta, 34, 08003 Barcelona',
    maps: 'https://goo.gl/maps/ABC1234',
    logo: 'https://random-image-url.com/logo1.jpg',
    banner: 'assets/img/fav3.png',
    description:
        'Famosa discoteca junto a la playa, con DJ internacionales y eventos exclusivos.',
    instagram: 'https://www.instagram.com/opiumbarcelona/',
    facebook: 'https://www.facebook.com/opiumbarcelona',
    twitter: 'https://twitter.com/OpiumBarcelona',
    tiktok: 'https://www.tiktok.com/@opiumbarcelona',
    time: '12:00 AM - 6:00 AM',
    capacity: 2000,
    musicGenre: ['House', 'Commercial'],
    vip: true,
    smookingArea: true,
    parking: false,
    promoted: true,
    longitude: 2.1945,
    latitude: 41.3851,
    favorite: false,
    province: 'Barcelona',
    city: 'Barcelona',
  ),
  const Discoteca(
     id:'2',
    name: 'Pacha Barcelona',
    address: 'Passeig Marítim de la Barceloneta, 38, 08003 Barcelona',
    maps: 'https://goo.gl/maps/DEF5678',
    logo: 'https://random-image-url.com/logo2.jpg',
    banner: 'assets/img/Disco2.png',
    description:
        'Discoteca emblemática con el clásico estilo Pacha, famosa por sus fiestas de música electrónica.',
    instagram: 'https://www.instagram.com/pachabarcelona/',
    facebook: 'https://www.facebook.com/pachabarcelona',
    twitter: 'https://twitter.com/PachaBarcelona',
    tiktok: 'https://www.tiktok.com/@pachabarcelona',
    time: '12:00 AM - 6:00 AM',
    capacity: 1500,
    musicGenre: ['Electronic', 'House'],
    vip: true,
    smookingArea: true,
    parking: true,
    promoted: true,
    longitude: 2.1955,
    latitude: 41.3862,
    favorite: true,
    province: 'Barcelona',
    city: 'Barcelona',
  ),
  const Discoteca(
    id:'3',
    name: 'Sutton Barcelona',
    address: 'Carrer de Tuset, 13, 08006 Barcelona',
    maps: 'https://goo.gl/maps/GHI7890',
    logo: 'https://random-image-url.com/logo3.jpg',
    banner: 'assets/img/fav3.png',
    description:
        'Exclusiva discoteca con un público de alto nivel, conocida por sus eventos glamurosos.',
    instagram: 'https://www.instagram.com/suttonbarcelona/',
    facebook: 'https://www.facebook.com/suttonclub',
    twitter: 'https://twitter.com/SuttonClubBCN',
    tiktok: 'https://www.tiktok.com/@suttonbarcelona',
    time: '11:30 PM - 6:00 AM',
    capacity: 1000,
    musicGenre: ['House', 'Commercial'],
    vip: true,
    smookingArea: true,
    parking: true,
    promoted: false,
    longitude: 2.1573,
    latitude: 41.3927,
    favorite: false,
    province: 'Barcelona',
    city: 'Barcelona',
  ),
  const Discoteca(
    id:'4',
    name: 'Shoko Barcelona',
    address: 'Passeig Marítim de la Barceloneta, 36, 08003 Barcelona',
    maps: 'https://goo.gl/maps/JKL1234',
    logo: 'https://random-image-url.com/logo4.jpg',
    banner: 'assets/img/Disco1.png',
    description:
        'Discoteca frente a la playa, combinando un restaurante y una pista de baile en un mismo lugar.',
    instagram: 'https://www.instagram.com/shokobarcelona/',
    facebook: 'https://www.facebook.com/shokobarcelona',
    twitter: 'https://twitter.com/ShokoBarcelona',
    tiktok: 'https://www.tiktok.com/@shokobarcelona',
    time: '12:00 AM - 5:30 AM',
    capacity: 1500,
    musicGenre: ['House', 'Hip-Hop'],
    vip: true,
    smookingArea: true,
    parking: true,
    promoted: true,
    longitude: 2.1938,
    latitude: 41.3859,
    favorite: true,
    province: 'Barcelona',
    city: 'Barcelona',
  ),
  const Discoteca(
    id:'5',
    name: 'Razzmatazz',
    address: 'Carrer dels Almogàvers, 122, 08018 Barcelona',
    maps: 'https://goo.gl/maps/MNO4567',
    logo: 'https://random-image-url.com/logo5.jpg',
    banner: 'assets/img/Disco2.png',
    description:
        'Una de las discotecas más grandes de Barcelona, famosa por sus múltiples pistas de baile y géneros variados.',
    instagram: 'https://www.instagram.com/razzmatazzclubs/',
    facebook: 'https://www.facebook.com/RazzmatazzClubs',
    twitter: 'https://twitter.com/RazzmatazzClubs',
    tiktok: 'https://www.tiktok.com/@razzmatazz',
    time: '12:00 AM - 6:00 AM',
    capacity: 3000,
    musicGenre: ['Indie', 'Rock', 'Electronic'],
    vip: true,
    smookingArea: true,
    parking: true,
    promoted: false,
    longitude: 2.1873,
    latitude: 41.3974,
    favorite: false,
    province: 'Barcelona',
    city: 'Barcelona',
  ),
  const Discoteca(
    id:'6',
    name: 'Bling Bling',
    address: 'Carrer de Tuset, 8, 08006 Barcelona',
    maps: 'https://goo.gl/maps/PQR7890',
    logo: 'https://random-image-url.com/logo6.jpg',
    banner: 'assets/img/fav3.png',
    description:
        'Una de las discotecas más lujosas de la ciudad, conocida por su ambiente exclusivo.',
    instagram: 'https://www.instagram.com/blingblingbcn/',
    facebook: 'https://www.facebook.com/blingblingbarcelona',
    twitter: 'https://twitter.com/BlingBlingBCN',
    tiktok: 'https://www.tiktok.com/@blingblingbcn',
    time: '11:30 PM - 6:00 AM',
    capacity: 1200,
    musicGenre: ['House', 'Commercial'],
    vip: true,
    smookingArea: true,
    parking: true,
    promoted: true,
    longitude: 2.1558,
    latitude: 41.3920,
    favorite: true,
    province: 'Barcelona',
    city: 'Barcelona',
  ),
  const Discoteca(
    id:'7',
    name: 'Input High Fidelity Club',
    address: 'Av. Francesc Ferrer i Guàrdia, 13, 08038 Barcelona',
    maps: 'https://goo.gl/maps/STU1234',
    logo: 'https://random-image-url.com/logo7.jpg',
    banner: 'assets/img/Disco1.png',
    description:
        'Discoteca de estilo industrial con un sistema de sonido de alta fidelidad.',
    instagram: 'https://www.instagram.com/inputbcn/',
    facebook: 'https://www.facebook.com/InputBCN',
    twitter: 'https://twitter.com/InputBCN',
    tiktok: 'https://www.tiktok.com/@inputbcn',
    time: '12:00 AM - 6:00 AM',
    capacity: 1200,
    musicGenre: ['Techno', 'Electronic'],
    vip: false,
    smookingArea: true,
    parking: true,
    promoted: true,
    longitude: 2.1514,
    latitude: 41.3651,
    favorite: false,
    province: 'Barcelona',
    city: 'Barcelona',
  ),
  const Discoteca(
    id:'8',
    name: 'La Terrrazza',
    address:
        'Poble Espanyol, Av. Francesc Ferrer i Guàrdia, 13, 08038 Barcelona',
    maps: 'https://goo.gl/maps/VWX4567',
    logo: 'https://random-image-url.com/logo8.jpg',
    banner: 'assets/img/fav3.png',
    description:
        'Discoteca al aire libre en Poble Espanyol, famosa por sus noches de house y techno.',
    instagram: 'https://www.instagram.com/laterrrazza/',
    facebook: 'https://www.facebook.com/laterrrazzabcn',
    twitter: 'https://twitter.com/LaTerrrazza',
    tiktok: 'https://www.tiktok.com/@laterrrazza',
    time: '11:30 PM - 6:00 AM',
    capacity: 1500,
    musicGenre: ['House', 'Techno'],
    vip: false,
    smookingArea: true,
    parking: true,
    promoted: false,
    longitude: 2.1511,
    latitude: 41.3658,
    favorite: true,
    province: 'Barcelona',
    city: 'Barcelona',
  ),
];
